name: easy_video
description: A new Flutter package project.
version: 0.0.1
homepage: https://tech.fighttech.vn

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chewie: ^1.3.5
  flutter:
    sdk: flutter

  video_player: ^2.4.7
  visibility_detector: ^0.3.3
  flick_video_player: 0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
